In [3]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]

x_data = torch.tensor(data)

print(f"Tensor: \n {x_data} \n")

np_array = np.array(data)

print(f"Numpy array: \n {np_array} \n")



Tensor: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy array: 
 [[1 2]
 [3 4]] 



In [4]:

x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"rand tensor: \n {x_rand} \n")

x_from_numpy = torch.from_numpy(np_array)
print(f"tensor from numpy: \n {x_from_numpy} \n")


Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

rand tensor: 
 tensor([[0.8750, 0.3996],
        [0.4083, 0.3590]]) 

tensor from numpy: 
 tensor([[1, 2],
        [3, 4]]) 



In [7]:
device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else "cpu"
print(device)
x_ones = x_ones.to(device)
print(f"Tensor is on: \n {x_ones.device} \n")



mps
Tensor is on: 
 mps:0 



In [14]:

tensor = torch.ones(4, 4)
tensor[:, 1] = 0

print(tensor)

t0 = torch.cat([tensor, tensor, tensor], dim = 0)
print(t0)



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [15]:

t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [17]:

print(f"tensor.mul(tensor) element wise multiply : \n {tensor.mul(tensor)} \n")



tensor.mul(tensor) element wise multiply : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [18]:
# Alternative syntax for element wise multiply :

print(f"tensor * tensor \n {tensor * tensor}")



tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [19]:
# matrix multiplication

print(f"tensor.matmul(tensor.T) matrix multiply : \n {tensor.matmul(tensor.T)} \n")



tensor.matmul(tensor.T) matrix multiply : 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



In [20]:
# Alternative syntax for matrix multiply : 
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")


tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In-place operations Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.

In [21]:

print(tensor, "\n")
tensor.add_(5)
print(tensor)






tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
