In [1]:
import torch
import torchvision
import torchaudio
import numpy as np


print("PyTorch version    :", torch.__version__)
print("Torchvision version:", torchvision.__version__)
print("Torchaudio version :", torchaudio.__version__)
print("CUDA version       :", torch.version.cuda)
print("cuDNN version      :", torch.backends.cudnn.version())
print("NumPy version      :", np.__version__)


if hasattr(torch, 'accelerator'):
    print("torch.accelerator is available\n")
    device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else "cpu"
else:
    print("torch.accelerator is NOT available\n")
    if torch.backends.mps.is_available():
        device = "mps"
    elif torch.cuda.is_available():
        device = "cuda"
    else:
        device = "cpu"

print("Selected device    :", device)


PyTorch version    : 2.0.1+cu117
Torchvision version: 0.15.2+cu117
Torchaudio version : 2.0.2+cu117
CUDA version       : 11.7
cuDNN version      : 8500
NumPy version      : 1.24.4
torch.accelerator is NOT available

Selected device    : cuda


In [2]:
data = [[1, 2], [3, 4]]

x_data = torch.tensor(data)

print(f"Tensor: \n {x_data} \n")

np_array = np.array(data)

print(f"Numpy array: \n {np_array} \n")

Tensor: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy array: 
 [[1 2]
 [3 4]] 



In [3]:

x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"rand tensor: \n {x_rand} \n")

x_from_numpy = torch.from_numpy(np_array)
print(f"tensor from numpy: \n {x_from_numpy} \n")


Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

rand tensor: 
 tensor([[0.1694, 0.3297],
        [0.2206, 0.8301]]) 

tensor from numpy: 
 tensor([[1, 2],
        [3, 4]]) 



In [4]:

x_ones = x_ones.to(device)
print(f"Tensor is on: \n {x_ones.device} \n")



Tensor is on: 
 cuda:0 



In [5]:

tensor = torch.ones(4, 4)
tensor[:, 1] = 0

print(tensor)

t0 = torch.cat([tensor, tensor, tensor], dim = 0)
print(t0)



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [6]:

t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [7]:

print(f"tensor.mul(tensor) element wise multiply : \n {tensor.mul(tensor)} \n")



tensor.mul(tensor) element wise multiply : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [8]:
# Alternative syntax for element wise multiply :

print(f"tensor * tensor \n {tensor * tensor}")



tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# matrix multiplication

print(f"tensor.matmul(tensor.T) matrix multiply : \n {tensor.matmul(tensor.T)} \n")



tensor.matmul(tensor.T) matrix multiply : 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



In [10]:
# Alternative syntax for matrix multiply : 
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")


tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In-place operations Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.

In [11]:

print(tensor, "\n")
tensor.add_(5)
print(tensor)






tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
